accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.generic import RedirectView

from accountapp.views import hello_world, hello_worlds, hello_world2, AccountCreateView, AccountDetailView
from accountapp.views import AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    #함수형 view형식
    path('hello_world/', hello_world, name='hello_world'),    #라우트, 뷰의 함수, 이름설정
    path('hello_worlds/', hello_worlds, name='hello_worlds'),  # 라우트, 뷰함수, 이름설정
    #즉, account/hello_world/ 가 들어오면, view의 hello_world라는 함수로 처리한다. 그 아래도 마찬가지
    path('hello_world2/', hello_world2, name='hello_world2'),

    #path("", hello_world2, name='hello_world2'),
    #path("http://127.0.0.1:8000/",  hello_world2, name='hello_world2'),

    #회원가입 경로 생성. CBV
    path('create/', AccountCreateView.as_view(), name='create'),

    #로그인,로그아웃
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),                #as_view()안에 지정 템플릿이 필요하다
    path('logout/', LogoutView.as_view(), name='logout'),

    #detail. 특정 유저의 정보를 보기 => 계정의 primary key가 필요하다. -> <int:pk> pk라는 이름의 정수를 받겠다.
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

]


#class HelloWorld(models.Model):

pragmatic/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),               #admin접속
    path('accounts/', include('accountapp.urls')), #account접속, accoutnapp내부의 urls.py를 포함해서 하위 디렉토리로 분기.  account => accounts로 변경
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),

                  ##path('junho/', views.index),  #junho/ URL이 요청되면 views.index를 호출매핑을 urlpatterns에 추가. views.index는 views.py 파일의 index 함수를 의미한다.

    #path("", RedirectView.as_view(url="accounts/hello_world2/", permanent=True))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),

]

accountapp/models.py
from django.db import models

# Create your models here.
class HelloWorld(models.Model):   #Model상속
    text = models.CharField(max_length=255, null=False)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
# Create your views here.
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from accountapp.models import HelloWorld

has_owership = [account_ownership_required, login_required]



#CBV로 만들기.FBV보다 낫다.
class AccountCreateView(CreateView):
    model = User                                           #장고 기본 제공 모델
    form_class = UserCreationForm                          #장고 기본 폼 제공
    success_url = reverse_lazy('accountapp:hello_world2')  #계정 생성 성공 후 어디로 연결할 것인가?..reverser_lazy는 class, reverse는 함수에서 사용
    template_name = 'accountapp/create.html'               #회원가입시 어떤 html을 통해서 볼지 설정. 즉, create.html이 필요하다


class AccountDetailView(DetailView):
    model = User                                         #어떤 모델을 쓸지?
    template_name = 'accountapp/detail.html'             #어떻게 보여줄지?
    context_object_name = 'target_user'                  #템플릿에서 사용하는 user이름의 객체를 다르게 할 수 있다. 다른사람이 내 페이지를 와도 정상적으로 타깃유저것을 보게한다.



@method_decorator(has_owership, 'get')
@method_decorator(has_owership, 'post')

class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:hello_world2')  #계정 성공 후 재연결..reverser_lazy는 class, reverse는 함수에서 사용
    template_name = 'accountapp/update.html'               #어느 html을 통해서 볼지 설정. create.html이 필요하다


@method_decorator(has_owership, 'get')
@method_decorator(has_owership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'               #어느 html을 통해서 볼지 설정. create.html이 필요하다






'''
def hello_world(request):
    return HttpResponse("hello worldsss")
   
    #HttpResponse는 요청 페이지에 대한 응답을 할때 사용하는 장고 클래스이다. 
    #hello_world 함수의 매개변수 request는 장고에 의해 자동으로 전달되는 HTTP 요청 객체이다.
    #request에 대해서는 조금 후에 더 자세히 알아보자.
    #view에서 직접 만들어서 되돌려 주는 형식




def hello_world(request):
    return render(request, 'base.html')  #templates의 base.html 반환
                                         #pragmatic.setting.py의 TEMPLATES에서 경로를 설정해줘야한다.

'''
def hello_world(request):
    return render(request, 'accountapp/hello_world.html')    #base.html이면, base.html을 가져오겠지? 우리는 accountapp내부의 정보가 필요하다


@login_required
def hello_world2(request):

    if request.method == "POST":
        temp = request.POST.get('hello_world_input')

        new_Hello_world = HelloWorld()
        new_Hello_world.text = temp
        new_Hello_world.save()

        return HttpResponseRedirect(reverse('accountapp:hello_world2'))

    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world2.html', context={'hello_world_list': hello_world_list})









def hello_worlds(request):
    return HttpResponse("hello world!!!!!!!!!!")
    #HttpResponse는 요청 페이지에 대한 응답을 할때 사용하는 장고 클래스이다.
    #라는 문자열을 브라우저에 출력하기 위해 사용되었다. index 함수의 매개변수 request는 장고에 의해 자동으로 전달되는 HTTP 요청 객체이다.
    #request에 대해서는 조금 후에 더 자세히 알아보자.

#hello_world_input을 {{ text }}에서 출력하는 것

'''
def hello_world2(request):
    #인증과정 만들기
    if request.user.is_authenticated:  #만약 유저가 인증되었다면,
        if request.method == "POST":   #만약 요청받은 매소드가 post일 경우, POST 매소드는 객체 생성시 사용된다.
            ##hello_world_input을 {{ text }}에서 출력하는 것
            temp = request.POST.get('hello_world_input')    #request에서 POST메서드 중, hello_world_input데이터를 가져와 temp변수에 저장
        
            #저장하는 방법
            new_Hello_world = HelloWorld()  #HelloWorld 모델에서 나온 새로운 객체가 new_hello_world에 저장이 된다.
            new_Hello_world.text = temp     #HelloWorld는 text라는 charfield라는 속성값이 있다. new_Hello_world안의 text필드 = temp(입력값)으로 설정
            new_Hello_world.save()          #실제로 db에 저장된다.(우선은 sqlite에)

            #db에 쌓이는 정보list들을 display하는 법
            hello_world_list = HelloWorld.objects.all()   #HelloWorld의 모든 것들을 긁어와 변수에 저장

            #return render(request, 'accountapp/hello_world2.html', context={'text': 'POST METHOD!!!'})  #context=>데이터꾸러미..? text라는 이름의 POST METHOD라는 내용물을 보냄. html에 {{ text }}로
            #return render(request, 'accountapp/hello_world2.html', context={'hello_world_output': new_hello_world}) #new_hello_world객체를 내보낸다. html에서 hello_world_output 명시 필수
            #return render(request, 'accountapp/hello_world2.html', context={'hello_world_list': hello_world_list})  #받을 것을 그대로 보내준다. 반복하는 문제가 생긴다.
            return HttpResponseRedirect(reverse('accountapp:hello_world2'))  #(account/hello_world2)를 해도 된다.
                                                                         #초기에 설정한 것 이용. accountapp내부의 hello_world2를 재섭속해라

        else:                        #만약 요청받은 매소드가 post가 아닌 경우, get매소드 사용

            #GET에서도 똑같은 행동을 할수 있도록 설정
            hello_world_list = HelloWorld.objects.all()
            #return render(request, 'accountapp/hello_world2.html', context={'text': 'GET METHOD!!!'})  # context=>데이터꾸러미..? text라는 이름의 POST METHOD라는 내용물
            return render(request, 'accountapp/hello_world2.html', context={'hello_world_list': hello_world_list})  # context=>데이터꾸러미..? text라는 이름의 POST METHOD라는 내용물

    else:  #로그인 안 된 경우 로그인 페이지로 보내버리기
        return HttpResponseRedirect(reverse('accountapp:login'))'''

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}  <!-- 전에 만들어놓은 base.html(뼈대)를 가져온다. 이걸 사용하면, 가운데만 바꿀 수 있게-->

{% block content%}

    <div style="text-align: center">
        <form action="{% url 'accountapp:create' %}" method="post">          <!--form 액션 내부엔 요청 url이 필요하다. accountapp내부의 create라는 라우트로 연결하라-->
            {& csrf_token %}
            {{ form }}       <!-- view.py의 form_class = UserCreationForm -->

            <input type="submit" class="btn btn-primary">
        </form>
    </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}  <!-- 전에 만들어놓은 base.html(뼈대)를 가져온다. 이걸 사용하면, 가운데만 바꿀 수 있게-->
{% load bootstrap4 %}

{% block content%}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto ">
        <div class="mb-4">  <!-- margin bottom 4배 -->
            <h4>Quit</h4>
        </div>

        <form action="{% url 'accountapp:delete' pk=target_user.pk  %}" method="post">     <!--form 액션 내부엔 요청 url이 필요하다. accountapp내부의 delete라는 라우트로 연결하라-->
            {% csrf_token %}

            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-5">    <!--삭제버튼 생성-->
        </form>
    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}  <!-- 전에 만들어놓은 base.html(뼈대)를 가져온다. 이걸 사용하면, 가운데만 바꿀 수 있게-->
{% load bootstrap4 %}

{% block content%}

    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto;">

             <!-- target_user의 profile이 존재하면, -->
            {% if target_user.profile %}
            <img src="{{ target_user.profile.image.url }}" alt="">  <!-- 사진 -->

            <h2 style="font-family: 'NanumSquareB'">
                {{ target_user.profile.nickname }}          <!--어서오세요 {{ target_user.username }}님 에서, 프로필이 있으면 닉네임 보여주는 걸로 변경-->
                    {% if target_user == user %}
                    <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                        Edit
                    </a>
                    {% endif %}
            </h2>
            <h5 style="margin-bottom:3rem;">
                {{ target_user.profile.message }}
            </h5>

            {% else %}                                       <!-- Profile이 아직 없는 경우..! profileapp의 create/profile로 이동시켜 만드는 페이지로 보내버림-->
                {% if target_user == user %}
                <a href="{% url 'profileapp:create' %}">
                    <h2 style="font-family: 'NanumSquareB'">
                        Create Profile
                    </h2>
                </a>
                {% else %}
                <h2>
                    아직 닉네임이 미설정입니다.
                </h2>
                {% endif %}
            {% endif %}



            {% if target_user == user %}  <!--만약 target유저가 접속한 유저와 같다면 이것을 보여준다. -->
            <a href="{% url 'accountapp:update' pk=user.pk %}">  <!--버튼을 누르면 ~~~~/update/pk숫자 url로 이동-->
                <p>
                    Change Info
                </p>
            </a>
            <a href="{% url 'accountapp:delete' pk=user.pk %}">   <!--버튼을 누르면 ~~~~/delete/pk숫자 url로 이동-->
                <p>
                    Quit
                </p>
            </a>
            {% endif %}
        </div>
    </div>


{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}  <!-- 전에 만들어놓은 base.html(뼈대)를 가져온다. 이걸 사용하면, 가운데만 바꿀 수 있게-->

{% block content%}

    <style>
        .testing{
            background-color: white;
            height: 3rem;
            width: 3rem;
            margin: 1rem;

        }
    </style>




     <div style="height: 20rem; background-color: #38df81; border-radius: 1rem; margin: 2rem">    <!-- div는 가능한 폭을 모두 쓴다. -->
         <h1>

             testing
         </h1>

         <div class="testing" style="display: inline-block; width: 48px; height: 48px;">block</div>
         <div class="testing" style="display: inline-block; width: 3em; height: 3em;">block</div>
         <div class="testing" style="display: inline-block; width: 3rem; height: 3rem;">block</div>
         <div class="testing" style="display: inline-block; width: 30%; height: 30%;">block</div>

     </div>

{% endblock %}

accountapp/templates/accountapp/hello_world2.html
{% extends 'base.html' %}  <!-- 전에 만들어놓은 base.html(뼈대)를 가져온다. 이걸 사용하면, 가운데만 바꿀 수 있게-->

{% block content%}

     <div style="border-radius: 1rem; margin: 2rem; text-align: center">
         <h1 class="pragmatic_logo">
            Hello world List!
         </h1>

        <!-- post를 쓰려면 form(데이터 꾸러미)을 써야한다.-->
         <form action="/account/hello_world2/" method="post">     <!--  해당 주소로 post매소드 사용해서 보내겠다 -->
            {% csrf_token %}
            <div> <!-- 서버로 보낼 내용-->
                <input type="text" name="hello_world_input">         <!--name?구분자! input에 hello_world_input이름 데이터를 담아서 서버로 보냄 -->
            </div>

            <input type="submit" class="btn btn_primary" value="POST">  <!-- 버튼 설정-->
         </form>

         {% if hello_world_list %}   <!-- 만약 hello_world_list가 있다면,  h1을 생성해라-->
            {% for hello_world in hello_world_list %}
            <h4>
                {{ hello_world.text }}
            </h4>
            {% endfor %}
         {% endif %}

     </div>

{% endblock %}

<!--<h1 class="pragmatic_logo">Pragmatic</h1>
            style="font-family: 'Lobster', cursive;"-->

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}  <!-- 전에 만들어놓은 base.html(뼈대)를 가져온다. 이걸 사용하면, 가운데만 바꿀 수 있게-->
{% load bootstrap4 %}

{% block content%}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto ">
        <div>
            <h4>Login!</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                <!-- {{ form }}  form을 쓰는 대신 부트스트랩 적용된 form 구문 사용-->
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-5">
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}  <!-- 전에 만들어놓은 base.html(뼈대)를 가져온다. 이걸 사용하면, 가운데만 바꿀 수 있게-->
{% load bootstrap4 %}

{% block content%}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">  <!-- margin bottom 4배 -->
            <h4>Change Info</h4>
        </div>

        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-5">
        </form>
    </div>

{% endblock %}