commentapp/urls.py
from commentapp.views import CommentCreateView

app_name = 'commentapp'
from django.urls import path

urlpatterns =[
    path('create/', CommentCreateView.as_view(), name='create'),

]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),               #admin접속
    path('accounts/', include('accountapp.urls')), #account접속, accoutnapp내부의 urls.py를 포함해서 하위 디렉토리로 분기.  account => accounts로 변경
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),

                  ##path('junho/', views.index),  #junho/ URL이 요청되면 views.index를 호출매핑을 urlpatterns에 추가. views.index는 views.py 파일의 index 함수를 의미한다.

    #path("", RedirectView.as_view(url="accounts/hello_world2/", permanent=True))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commentapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from articleapp.models import Article


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.SET_NULL, null=True, related_name='comment')
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='comment')

    content = models.TextField(null=False)

    created_at = models.DateTimeField(auto_now=True)

commentapp/forms.py
from django.forms import ModelForm

from commentapp.models import Comment


class CommentCreationForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

commentapp/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views.generic import CreateView

from commentapp.forms import CommentCreationForm
from commentapp.models import Comment


class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentCreationForm
    template_name = 'commentapp/create.html'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.article.pk} )

commentapp/templates/commentapp/create.html
{% extends 'base.html' %}  <!-- 전에 만들어놓은 base.html(뼈대)를 가져온다. 이걸 사용하면, 가운데만 바꿀 수 있게-->
{% load bootstrap4 %}

{% block content%}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto ">
        <div class="mb-4">  <!-- margin bottom 4배 -->
            <h4>Comment Create</h4>
        </div>

        <form action="{% url 'commentapp:create' %}" method="post">          <!--form 액션 내부엔 요청 url이 필요하다. accountapp내부의 create라는 라우트로 연결하라-->
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-5">
            <input type="hidden" name="article_pk" value="">

        </form>
    </div>

{% endblock %}