accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.generic import RedirectView

from accountapp.views import hello_world, hello_worlds, hello_world2, AccountCreateView, AccountDetailView
from accountapp.views import AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    #함수형 view형식
    path('hello_world/', hello_world, name='hello_world'),    #라우트, 뷰의 함수, 이름설정
    path('hello_worlds/', hello_worlds, name='hello_worlds'),  # 라우트, 뷰함수, 이름설정
    #즉, account/hello_world/ 가 들어오면, view의 hello_world라는 함수로 처리한다. 그 아래도 마찬가지
    path('hello_world2/', hello_world2, name='hello_world2'),

    #path("", hello_world2, name='hello_world2'),
    #path("http://127.0.0.1:8000/",  hello_world2, name='hello_world2'),

    #회원가입 경로 생성. CBV
    path('create/', AccountCreateView.as_view(), name='create'),

    #로그인,로그아웃
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),                #as_view()안에 지정 템플릿이 필요하다
    path('logout/', LogoutView.as_view(), name='logout'),

    #detail. 특정 유저의 정보를 보기 => 계정의 primary key가 필요하다. -> <int:pk> pk라는 이름의 정수를 받겠다.
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

]


#class HelloWorld(models.Model):

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),

]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),               #admin접속
    path('accounts/', include('accountapp.urls')), #account접속, accoutnapp내부의 urls.py를 포함해서 하위 디렉토리로 분기.  account => accounts로 변경
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),

                  ##path('junho/', views.index),  #junho/ URL이 요청되면 views.index를 호출매핑을 urlpatterns에 추가. views.index는 views.py 파일의 index 함수를 의미한다.

    #path("", RedirectView.as_view(url="accounts/hello_world2/", permanent=True))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}  <!-- head.html을 다 갖고올 수 있다. -->

<body style="font-family: 'NanumSquareR';">   <!-- 3부분으로 나누기 위, 아래 부분은 그대로 인데 중간만 바뀌는 게 핵심-->

    {% include 'header.html' %}

    <hr>  <!-- 구분선 -->

    {% block content %}  <!-- content라는 블럭 나머지는 재사용 하면서, content부분만 바꿔주기-->
    {% endblock %}


    <hr>  <!-- 구분선 -->

    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
    <div class="pragmatic_footer">

        <div class="pragmatic_footer_button">
            <span>공지사항</span>  |
            <span>제휴문의</span>  |
            <span>서비스소개</span>

        </div>
        <div style="margin-top: 1rem;">
            <h6 class="pragmatic_logo">Pragmatic</h6>
        </div>

    </div>









    <!-- css적용전
        <div style="text-align:center; margin-top: 2rem;"> div는 가능한 폭을 모두 쓴다.

        <div style="font-size: .6rem;">
            <span>공지사항</span>  |
            <span>제휴문의</span>  |
            <span>서비스소개</span>
        </div>
        <div style="margin-top: 1rem;">
            <h6 style="font-family: 'Lobster', cursive;">Pragmatic</h6>
        </div>
    </div>
    -->

templates/head.html
<!--head요소는 해당 웹페이지에 직접적으로 표현되지는 않으나, 이 페이지의 제목이나 웹페이지가 검색엔진에 노출이 될 수 있도록
하는 각종 정보('메타데이터'라고 한다)들을 담는 역할을 한다.
웹페이지를 꾸미는 CSS파일이나 자바스크립트 JS 파일을 연결하는 부분 또한 주로 head 요소 안에 위치한다.-->


{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Pragmatic</title>
    <!-- bootstrap 링크 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- 구글 폰트 링크 -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

    <!-- DEFAULT CSS LINK    -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">


    <style>
        @font-face{
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.ttf' %}") format("opentype");
        }
        @font-face{
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face{
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face{
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }

    </style>

</head>





<!-- css 적용전
<head>
    <meta charset="UTF-8">
    <title>Pragmatic</title>
     bootstrap 링크
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

     구글 폰트 링크
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

</head> -->

templates/header.html
    <div class="pragmatic_header">
        <div>
            <h1 class="pragmatic_logo">Pragmatic</h1>

        </div>
        <div>
            <a href="{% url 'articleapp:list' %}">
                <span>Articles</span>
            </a>
            <span>nav2</span>
            <span>nav3</span>

            <!--로그인 만들기-->
            {% if not user.is_authenticated %}        <!--만약 유저가 로그인이 되어있지 않다면 login을 보여주고-->
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}">   <!--login이후가 필요하다. get방식으로 넘겨주기. request.path는 원래 있던 곳으로 돌아오기-->
                <span>login</span>
            </a>

            <a href="{% url 'accountapp:create' %}">   <!--버튼 누르면 account/create로 이동-->
                <span>Sign Up</span>
            </a>


            {% else %}                               <!--login상태라면 mypage로 향하는 링크 생성 ㄱㄱ-->
            <a href="{% url 'accountapp:detail' pk=user.pk %}">
                <span>Mypage</span>
            </a>

            <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
                <span>logout</span>
            </a>
            {% endif %}
        </div>

    </div>




<!--     css적용전
    <div style="text-align:center; margin: 2rem 0; ">
        <div>
            <h1 style="font-family: 'Lobster', cursive;">Pragmatic</h1>
        </div>
        <div>
            <span>nav1</span>
            <span>nav1</span>
            <span>nav1</span>
            <span>nav1</span>
        </div>

    </div>                     헤더 부분도 이렇게 나눌 수 있다. -->